#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_2
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_17
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_16
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_15

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_8
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_18
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

// Sensor dock I2C (ESP32-S3-BOX-3-SENSOR / PMOD expander bus)
#define DOCK_I2C_SCL_PIN GPIO_NUM_40
#define DOCK_I2C_SDA_PIN GPIO_NUM_41

// Sensor dock peripherals (from Espressif ESP-BOX factory demo BSP)
#define RADAR_OUT_PIN    GPIO_NUM_21
#define IR_CTRL_PIN      GPIO_NUM_44
#define IR_TX_PIN        GPIO_NUM_39
#define IR_RX_PIN        GPIO_NUM_38

// PMOD pins (ESP32-S3-BOX-3 DOCK / BRACKET / BREAD adapters)
#define PMOD1_IO1 GPIO_NUM_42
#define PMOD1_IO2 GPIO_NUM_20
#define PMOD1_IO3 GPIO_NUM_39
#define PMOD1_IO4 GPIO_NUM_40
#define PMOD1_IO5 GPIO_NUM_21
#define PMOD1_IO6 GPIO_NUM_19
#define PMOD1_IO7 GPIO_NUM_38
#define PMOD1_IO8 GPIO_NUM_41

#define PMOD2_IO1 GPIO_NUM_13
#define PMOD2_IO2 GPIO_NUM_9
#define PMOD2_IO3 GPIO_NUM_12
#define PMOD2_IO4 GPIO_NUM_44
#define PMOD2_IO5 GPIO_NUM_10
#define PMOD2_IO6 GPIO_NUM_14
#define PMOD2_IO7 GPIO_NUM_11
#define PMOD2_IO8 GPIO_NUM_43

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_WIDTH   320
#define DISPLAY_HEIGHT  240
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_47
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false


#endif // _BOARD_CONFIG_H_
