#!/usr/bin/env python3
"""
Generate embedded frontal head point-splat from a placeholder 'generic male head' point set.

We build a dense point cloud on a deformed sphere (front hemisphere), project to XY,
approximate Lambert shading for a frontal key light, then subsample to kTarget points.

Firmware note: the same algorithm is embedded at boot in `main/display/jarvis_point_cloud.cc`
(`BuildGenericMaleHeadMesh`) so the device does not require the generated `.inc` at build time.
Keep this script + OBJ export for artist swaps and visual diffing.

Output: main/display/data/jarvis_head_mesh.inc (C++ constexpr tables)

Optional: writes scripts/out/generic_male_head_points.obj (vertex-only OBJ for artist swap).
"""
from __future__ import annotations

import math
import os

# Match firmware: keep total draw cost in check for >= ~25 FPS on BOX3 canvas.
K_TARGET = 168

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_INC = os.path.normpath(
    os.path.join(SCRIPT_DIR, "..", "main", "display", "data", "jarvis_head_mesh.inc")
)
OUT_OBJ = os.path.join(SCRIPT_DIR, "out", "generic_male_head_points.obj")


def fibonacci_sphere(n: int, scale: float = 1.0) -> list[tuple[float, float, float]]:
    pts: list[tuple[float, float, float]] = []
    golden = (1.0 + math.sqrt(5.0)) / 2.0
    for i in range(n):
        t = (i + 0.5) / n
        y = 1.0 - 2.0 * t
        r = math.sqrt(max(0.0, 1.0 - y * y))
        theta = 2.0 * math.pi * i / golden
        x = math.cos(theta) * r * scale
        z = math.sin(theta) * r * scale
        y *= scale
        pts.append((x, y, z))
    return pts


def head_deform(x: float, y: float, z: float) -> tuple[float, float, float]:
    """Proportions similar to a neutral adult male mask (frontal)."""
    x *= 0.92
    y = y * 1.12 - 0.04
    z *= 1.08
    # Nose bridge / tip
    nose = math.exp(-(x * x * 9.0 + (y - 0.05) ** 2 * 14.0)) * 0.14
    z = z + nose
    # Cheeks / jaw width
    x *= 1.0 + 0.11 * math.exp(-((abs(y) + 0.12) ** 2) * 4.0)
    # Brow / forehead
    y += 0.03 * math.exp(-(x * x * 5.0 + (y - 0.35) ** 2 * 8.0))
    return x, y, z


def vlen3(v: tuple[float, float, float]) -> float:
    return math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]) or 1.0


def normalize(v: tuple[float, float, float]) -> tuple[float, float, float]:
    l = vlen3(v)
    return v[0] / l, v[1] / l, v[2] / l


def dot(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def main() -> None:
    light = (0.0, 0.0, 1.0)
    raw: list[tuple[float, float, float, float]] = []
    for x, y, z in fibonacci_sphere(520, 1.0):
        x, y, z = head_deform(x, y, z)
        if z < -0.22:
            continue
        n = normalize((x, y * 1.08, z + 0.18))
        shade = max(0.0, min(1.0, dot(n, light)))
        # Screen: +Y down → store sy = -y
        raw.append((x, -y, shade))

    # Farthest-point seeding (greedy, O(n*k) — n~300, k=168 OK)
    candidates = raw[:]
    chosen: list[tuple[float, float, float]] = []
    # Start near nose
    start = min(candidates, key=lambda p: p[0] * p[0] + (p[1] - 0.08) ** 2)
    candidates.remove(start)
    chosen.append(start)
    while len(chosen) < K_TARGET and candidates:
        best_i = -1
        best_d2 = -1.0
        for i, p in enumerate(candidates):
            d2 = min((p[0] - q[0]) ** 2 + (p[1] - q[1]) ** 2 for q in chosen)
            if d2 > best_d2:
                best_d2 = d2
                best_i = i
        chosen.append(candidates.pop(best_i))

    # Normalize XY to ~[-0.78, 0.78]
    xs = [p[0] for p in chosen]
    ys = [p[1] for p in chosen]
    mx = max(abs(min(xs)), abs(max(xs)), 1e-6)
    my = max(abs(min(ys)), abs(max(ys)), 1e-6)
    m = max(mx, my)
    norm = [(p[0] / m * 0.78, p[1] / m * 0.78, p[2]) for p in chosen]

    os.makedirs(os.path.dirname(OUT_INC), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_OBJ), exist_ok=True)

    with open(OUT_INC, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scripts/gen_jarvis_head_mesh.py — do not edit. */\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write(f"static constexpr int kJarvisHeadMeshPoints = {len(norm)};\n\n")
        f.write(f"static constexpr float kJarvisHeadMeshX[{len(norm)}] = {{\n")
        f.write(",\n".join(f"    {v[0]:.6f}f" for v in norm))
        f.write("\n};\n\n")
        f.write(f"static constexpr float kJarvisHeadMeshY[{len(norm)}] = {{\n")
        f.write(",\n".join(f"    {v[1]:.6f}f" for v in norm))
        f.write("\n};\n\n")
        shades_u8 = [int(max(0, min(255, round(s * 255.0)))) for _, _, s in norm]
        f.write(f"static constexpr uint8_t kJarvisHeadMeshShade[{len(norm)}] = {{\n")
        f.write(",\n".join(f"    {s}" for s in shades_u8))
        f.write("\n};\n")

    # Vertex-only OBJ (swap with a sculpted head later; regenerate .inc via this script).
    with open(OUT_OBJ, "w", encoding="utf-8") as fo:
        fo.write("# Generic male head POINT CLOUD (frontal approximation)\n")
        fo.write("# Replace with mesh vertices & re-run: python3 scripts/gen_jarvis_head_mesh.py\n")
        for x, y, s in norm:
            z_stub = (s - 0.5) * 0.4
            fo.write(f"v {x:.6f} {y:.6f} {z_stub:.6f}\n")

    print(f"Wrote {OUT_INC} ({len(norm)} points)")
    print(f"Wrote {OUT_OBJ}")


if __name__ == "__main__":
    main()
