#!/usr/bin/env python3
"""
Emit raw RGB565 pixels for Jarvis HUD face overlay (embedded in firmware).

Artist workflow:
  Drop a frontal PNG in jarvis_hud/samples/ as jarvis_face.png and extend this
  script with Pillow (resize → RGB565) to replace the deterministic placeholder mask.

Output: jarvis_hud/generated/jarvis_artist_face_data.c

The firmware builds lv_img_dsc_t from constants + pixel array in jarvis_artist_hud.cc.
"""

from __future__ import annotations

import math
import os
import struct

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
JARVIS_HUD_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))
OUT_C = os.path.join(JARVIS_HUD_ROOT, "generated", "jarvis_artist_face_data.c")


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | ((b >> 3) & 0x1F)


def build_mask(w: int, h: int) -> tuple[bytes, int]:
    """Soft frontal mask: HUD navy outside, cyan interior with rim highlight."""
    bg = rgb565(0x06, 0x10, 0x18)
    fg = rgb565(0x5E, 0xDE, 0xF5)
    rim = rgb565(0x2F, 0x8F, 0xA8)

    stride = w * 2
    pix = bytearray(h * stride)
    cx = w * 0.5
    cy = h * 0.46

    rx = w * 0.36
    ry = h * 0.44

    for y in range(h):
        for x in range(w):
            dx = (x - cx) / max(rx, 1e-3)
            dy = (y - cy) / max(ry, 1e-3)
            if dy > 0.15:
                dx *= 1.0 + 0.35 * ((dy - 0.15) / 1.05) ** 2
            nx = dx
            ny = dy
            d = math.sqrt(nx * nx + ny * ny)

            edge = math.exp(-((d - 0.94) ** 2) / 0.048)
            interior = math.exp(-(d * d) / 0.55)
            core = math.exp(-(d * d) / 0.42)
            t = max(0.0, min(1.0, interior))

            er = bg & 0xFF
            eg = (bg >> 8) & 0xFF

            rr = (((fg >> 11) & 0x1F) << 3) | (((fg >> 11) & 0x1F) >> 2)
            gg = ((fg >> 5) & 0x3F) << 2
            bb = ((fg & 0x1F) << 3) | ((fg & 0x1F) >> 2)

            r = int(er * (1 - t * 0.9) + rr * (t * 0.92))
            g_val = int(eg * (1 - t * 0.9) + gg * (t * 0.92))
            b_val = int(((bg & 0x1F) << 3) * (1 - t * 0.9) + bb * (t * 0.92))

            e2 = edge * (1 - core * 0.35)
            r = int(min(255, r + ((((rim >> 11) & 0x1F) << 3) * e2 * 0.35)))
            g_val = int(min(255, g_val + ((((rim >> 5) & 0x3F) << 2) * e2 * 0.35)))
            b_val = int(min(255, b_val + (((rim & 0x1F) << 3) * e2 * 0.35)))

            px = rgb565(r, g_val, b_val)
            idx = y * stride + x * 2
            pix[idx : idx + 2] = struct.pack("<H", px)

    return bytes(pix), stride


def emit_c(pix: bytes, w: int, h: int, stride: int) -> None:
    os.makedirs(os.path.dirname(OUT_C), exist_ok=True)
    data_size = len(pix)

    rows = []
    row = []
    for b in pix:
        row.append(f"0x{b:02X}")
        if len(row) == 12:
            rows.append(", ".join(row))
            row.clear()
    if row:
        rows.append(", ".join(row))

    body = ",\n    ".join(rows)

    txt = f"""/* AUTO-GENERATED BY jarvis_hud/tools/gen_jarvis_artist_face_asset.py */
#include <stdint.h>

const unsigned kJarvisArtistFace_w = {w};
const unsigned kJarvisArtistFace_h = {h};
const unsigned kJarvisArtistFace_stride = {stride};
const unsigned kJarvisArtistFace_data_size = {data_size};

const uint8_t kJarvisArtistFace_pixels[{data_size}] = {{
    {body}
}};
"""
    with open(OUT_C, "w", encoding="utf-8") as fo:
        fo.write(txt)
    print(f"Wrote {OUT_C} ({w}x{h} RGB565, {data_size} bytes)")


def main() -> None:
    w, h = 200, 240
    pix, stride = build_mask(w, h)
    if len(pix) != h * stride:
        raise SystemExit("internal stride mismatch")
    emit_c(pix, w, h, stride)


if __name__ == "__main__":
    main()
